# Generated by Django 6.0.3 on 2026-03-24 13:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('actual_age', models.IntegerField(blank=True, help_text='Age in numbers', null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('district', models.CharField(max_length=100)),
                ('district_code', models.CharField(max_length=20)),
                ('event_type', models.CharField(blank=True, choices=[('Phunaba-Ama', 'Phunaba-Ama'), ('Phunaba-Anishuba', 'Phunaba-Anishuba')], max_length=50, null=True)),
                ('age_category', models.CharField(choices=[('U14', 'Under 14'), ('U18', 'Under 18'), ('O18', 'Over 18')], help_text="Select the participant's age group.", max_length=3)),
                ('weight_category', models.CharField(choices=[('-21', '-21 Kg'), ('-25', '-25 Kg'), ('-29', '-29 Kg'), ('-33', '-33 Kg'), ('-37', '-37 Kg'), ('-40', '-40 Kg'), ('-41', '-41 Kg'), ('-44', '-44 Kg'), ('-45', '-45 Kg'), ('-49', '-49 Kg'), ('-52', '-52 Kg'), ('-53', '-53 Kg'), ('-56', '-56 Kg'), ('-75', '-75 Kg'), ('+53', '+53 Kg')], help_text="Select the participant's weight class.", max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle_rings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('JUDGE', 'Judge'), ('SCORER', 'Scorer')], default='SCORER', max_length=50)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('district_code', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('age_category', models.CharField(max_length=3)),
                ('weight_category', models.CharField(max_length=4)),
                ('gender', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('round_number', models.IntegerField(default=1)),
                ('match_sequence', models.IntegerField(help_text='Order of the match in this round')),
                ('current_sub_round', models.IntegerField(default=1)),
                ('ring_number', models.IntegerField(default=1)),
                ('participant_blue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_blue', to='thangta.participant')),
                ('participant_red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_red', to='thangta.participant')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='thangta.participant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thangta.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=1)),
                ('sub_round', models.IntegerField(default=1)),
                ('is_foul', models.BooleanField(default=False)),
                ('foul_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='thangta.match')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thangta.participant')),
                ('scorer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='thangta.tournament'),
        ),
    ]
