# Generated by Django 6.0.3 on 2026-03-20 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thangta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle_rings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('actual_age', models.IntegerField(blank=True, help_text='Age in numbers', null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('district', models.CharField(max_length=100)),
                ('district_code', models.CharField(max_length=20)),
                ('event_type', models.CharField(blank=True, choices=[('Phunaba-Ama', 'Phunaba-Ama'), ('Phunaba-Anishuba', 'Phunaba-Anishuba')], max_length=50, null=True)),
                ('age_category', models.CharField(choices=[('U14', 'Under 14'), ('U18', 'Under 18'), ('O18', 'Over 18')], help_text="Select the participant's age group.", max_length=3)),
                ('weight_category', models.CharField(choices=[('-21', '-21 Kg'), ('-25', '-25 Kg'), ('-29', '-29 Kg'), ('-33', '-33 Kg'), ('-37', '-37 Kg'), ('-40', '-40 Kg'), ('-41', '-41 Kg'), ('-44', '-44 Kg'), ('-45', '-45 Kg'), ('-49', '-49 Kg'), ('-52', '-52 Kg'), ('-53', '-53 Kg'), ('-56', '-56 Kg'), ('-75', '-75 Kg'), ('+53', '+53 Kg')], help_text="Select the participant's weight class.", max_length=4)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='thangta.tournament')),
            ],
        ),
    ]
