# Generated by Django 6.0.3 on 2026-03-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thangta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
    ]
