# Generated by Django 6.0.3 on 2026-03-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thangta', '0002_match_current_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='round_num',
            field=models.IntegerField(default=1),
        ),
    ]
