# Generated by Django 6.0.3 on 2026-03-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thangta', '0002_tournament_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='district_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
