# Generated by Django 6.0.3 on 2026-03-27 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thangta', '0003_score_round_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='sub_round',
        ),
    ]
