# Generated by Django 6.0.3 on 2026-03-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thangta', '0004_remove_score_sub_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('access_code', models.CharField(max_length=50)),
            ],
        ),
    ]
