# Generated by Django 6.0.3 on 2026-03-22 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thangta', '0004_alter_tournament_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('age_category', models.CharField(max_length=3)),
                ('weight_category', models.CharField(max_length=4)),
                ('gender', models.CharField(max_length=10)),
                ('round_number', models.IntegerField(default=1)),
                ('match_sequence', models.IntegerField(help_text='Order of the match in this round')),
                ('ring_number', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('participant_blue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_blue', to='thangta.participant')),
                ('participant_red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_red', to='thangta.participant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thangta.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='thangta.participant')),
            ],
        ),
    ]
