# Generated by Django 6.0.3 on 2026-03-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thangta', '0005_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
