# Generated by Django 6.0.3 on 2026-03-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thangta', '0006_match_is_active_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_sub_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='score',
            name='foul_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='is_foul',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='sub_round',
            field=models.IntegerField(default=1),
        ),
    ]
