# Generated by Django 6.0.3 on 2026-04-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thangta', '0006_participant_age_participant_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='sub_round',
            field=models.IntegerField(default=1),
        ),
    ]
