# Generated by Django 6.0.3 on 2026-04-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thangta', '0007_score_sub_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round_1_blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='round_1_red',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='round_2_blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='round_2_red',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='round_3_blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='round_3_red',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score_blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score_red',
            field=models.IntegerField(default=0),
        ),
    ]
