# Generated by Django 6.0.3 on 2026-04-02 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thangta', '0008_match_round_1_blue_match_round_1_red_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='active_scorers',
            field=models.ManyToManyField(blank=True, related_name='scoring_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
