# Generated by Django 6.0.3 on 2026-04-03 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thangta', '0009_match_active_scorers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='score_blue',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score_red',
        ),
    ]
