# Generated by Django 6.0.3 on 2026-04-07 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thangta', '0010_remove_match_score_blue_remove_match_score_red'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corner', models.CharField(max_length=10)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thangta.match')),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('match', 'scorer')},
            },
        ),
    ]
